apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dd3x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-dd3x@sha256:a464f413d62edd5ff61a90110fcb08f9d2662cdd520a930ded4d954dbc6a385f
        name: my-nodejs
        resources: {}
status: {}
